name: Readme Update

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Update README
        run: npm start
      - name: Commit README
        env:
          GITHUB_TOKEN: ${{ secrets.REP_TOKEN }}
        run: |
          git config --local user.email "diehreo@gmail.com"
          git config --local user.name "mag123c"
          git remote set-url origin https://x-access-token:${{ secrets.REP_TOKEN }}@github.com/${{ github.repository }}.git
          git add README.md
          git commit -m "Update README.md" || echo "No changes to commit"
          git push || echo "No changes to push"
